### ISSUE TITLE
Nan Return

### ISSUE THREAD

**Issue by Deamoner** [freshsomebody/posenet-similarity#4]
I was using the library and got the poses going into the function correctly. But the return is Nan. Any idea why that would return? 

My code is simple: 
console.log(poseSimilarity(pose1[0],pose2[0]))

**Comment by freshsomebody** [comment]
Hi @Deamoner , thank you for reporting!
I think it should be a mistake I made in the document.
If you are using estimate**Single**Pose, it should be poseSimilarity(pose1, pose2).
If you are using estimate**Multiple**Poses, then it should be poseSimilarity(pose1[0], pose2[0]).

I will fix the document. Could verify whether it solves the problem?

**Comment by Deamoner** [comment]
Hey Thanks for the prompt response. 

It appears the issue is a Nan return is done when the comparison poses keypoints are not equal. I was just showing face comparing to a full body shot. 
Thanks.
