### ISSUE TITLE
The keypoint lengths of the two pose objects are not the same

### ISSUE THREAD

**Issue by KarthickSelvam** [freshsomebody/posenet-similarity#6]
the pose estimation of a video and an image has different vectors i.e length of estimation params is different. 

How to avoid this?

**Comment by freshsomebody** [comment]
Hi @KarthickSelvam , thank you.

May I ask where were the two vectors with different lengths from?
From PoseNet or from this package?

**Comment by KarthickSelvam** [comment]
yup from PoseNet, but not from this package, I'm using react-posenet component.
Btw I was able to handle it something like this, i.e calling poseSimilarity() only if the lengths match.

if(pose[0] && imagePose[0] && imagePose[0].keypoints.length === pose[0].keypoints.length) {
      const similarity = poseSimilarity(imagePose[0], pose[0], { strategy: 'cosineDistance' });
}

**Comment by freshsomebody** [comment]
Thank you for the information!
Your if (...) looks okay. Is that not working now?

**Comment by KarthickSelvam** [comment]
Yes! Thanks!
